import Footer from "@/components/sections/footer";
import Header from "@/components/sections/header";
import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Font files can be colocated inside of `app`
const montserrat = localFont({
  variable: "--font-montserrat",
  display: "swap",
  src: [
    {
      path: "./../../public/fonts/Montserrat/static/Montserrat-Regular.ttf",
      weight: "400",
      style: "normal",
    },
    {
      path: "./../../public/fonts/Montserrat/static/Montserrat-Italic.ttf",
      weight: "400",
      style: "italic",
    },
    {
      path: "./../../public/fonts/Montserrat/static/Montserrat-SemiBold.ttf",
      weight: "600",
      style: "normal",
    },

    {
      path: "./../../public/fonts/Montserrat/static/Montserrat-ExtraBold.ttf",
      weight: "700",
      style: "normal",
    },
    {
      path: "./../../public/fonts/Montserrat/static/Montserrat-BlackItalic.ttf",
      weight: "700",
      style: "italic",
    },
  ],
});

const notoSans = localFont({
  variable: "--font-noto-sans",
  display: "swap",
  src: [
    {
      path: "./../../public/fonts/NotoSans/NotoSans-Regular.ttf",
      weight: "400",
      style: "normal",
    },
    {
      path: "./../../public/fonts/NotoSans/NotoSans-SemiBold.ttf",
      weight: "600",
      style: "semibold",
    },
  ],
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${montserrat.variable} ${notoSans.variable}`}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
